CREATE TABLE book
(
    book_id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    description         TEXT,
    author              VARCHAR(255),
    publishing_house    VARCHAR(255),
    language            VARCHAR(255),
    year_of_publication INTEGER,
    number_of_pages     VARCHAR(255),
    image               VARCHAR(255),
    users_id            INTEGER,
    preview_image_id    BIGINT,
    date_of_created     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_book PRIMARY KEY (book_id)
);

CREATE TABLE bucket
(
    bucket_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    users_id  INTEGER,
    CONSTRAINT pk_bucket PRIMARY KEY (bucket_id)
);

CREATE TABLE buckets_books
(
    book_id   INTEGER NOT NULL,
    bucket_id INTEGER NOT NULL
);

CREATE TABLE image
(
    image_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    original_file_name VARCHAR(255),
    size               BIGINT,
    content_type       VARCHAR(255),
    is_preview_image   BOOLEAN                                 NOT NULL,
    bytes              OID,
    book_book_id       INTEGER,
    CONSTRAINT pk_image PRIMARY KEY (image_id)
);

CREATE TABLE users
(
    users_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name   VARCHAR(255),
    second_name  VARCHAR(255),
    email        VARCHAR(255),
    username     VARCHAR(255),
    password     VARCHAR(255),
    phone_number VARCHAR(255),
    active       BOOLEAN                                  NOT NULL,
    role         VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (users_id)
);

ALTER TABLE book
    ADD CONSTRAINT FK_BOOK_ON_USERS FOREIGN KEY (users_id) REFERENCES users (users_id);

ALTER TABLE bucket
    ADD CONSTRAINT FK_BUCKET_ON_USERS FOREIGN KEY (users_id) REFERENCES users (users_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_BOOK_BOOK FOREIGN KEY (book_book_id) REFERENCES book (book_id);

ALTER TABLE buckets_books
    ADD CONSTRAINT fk_bucboo_on_book FOREIGN KEY (book_id) REFERENCES book (book_id);

ALTER TABLE buckets_books
    ADD CONSTRAINT fk_bucboo_on_bucket FOREIGN KEY (bucket_id) REFERENCES bucket (bucket_id);
